version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: 'app_${APP_NAME}'
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    environment:
      DB_HOST: mysql
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  nginx:
    image: nginx:alpine
    container_name: 'nginx_${APP_NAME}'
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www/html
    depends_on:
      - app
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: 'mysql_${APP_NAME}'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: 'phpmyadmin_${APP_NAME}'
  #   environment:
  #     PMA_HOST: mysql
  #     # PMA_USER: root
  #     # PMA_PASSWORD: root
  #     MYSQL_USER: ${DB_USERNAME}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     PMA_CONTROL_USER: ${DB_USERNAME}
  #     PMA_CONTROL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #   ports:
  #     - "8081:80"
  #   depends_on:
  #     - mysql
  #   networks:
  #     - app-network

volumes:
  mysql_data:

networks:
  app-network:
